### ISSUE TITLE
unable to open project

### ISSUE THREAD

**Issue by mahethekiller** [tripatheea/inventory-management#2]
when i open it on local host after setting database n all i redirects me to this url
http://store.globalcollegiate.edu.np/index.php/auth/login
Please help

**Comment by crbertoldo** [comment]
change it to 'localhost' in '/application_fa93g/config/config.php'

**Comment by mahethekiller** [comment]
its working now thanks , one more thing  ....  when you created new demo user what password encr. you used  ,

**Comment by tripatheea** [comment]
I think it's sha2. But you won't be able to just sha2-encrypt your password and put it in the database table because of salts. So when you add an entry in the aiap97af_users table, put a random text for the password field and then use the Forgot Password thingy.
