### ISSUE TITLE
Inventory Managemnet

### ISSUE THREAD

**Issue by grace43** [tripatheea/inventory-management#5]
when i try and access the project via Localhost

Not Found

The requested URL /index.php/ was not found on this server.

**Comment by nalimleinad** [comment]
Its .htaccess problem. Truncate it.

**Comment by NinioDev** [comment]
How can I add a new User? When I'm trying to Register i redirect me to login screen again, When I push it manually to database I have no idea how to write the password (its not working if its not encrypted).
Thanks.

**Comment by tripatheea** [comment]
When you add an entry in the aiap97af_users table, put a random text for the password field and then use the Forgot Password thingy.

**Comment by NinioDev** [comment]
Ill try it, thanks! :+1:
