### ISSUE TITLE
What is the user name and pw?

### ISSUE THREAD

**Issue by Klopko** [tripatheea/inventory-management#6]
Or in which file can I set it?

**Comment by tripatheea** [comment]
Do you mean the database username / password or the application username / password? For the former, you just have to specify it in application_fa93g/config/database.php. For the latter, you need to create an entry yourself in the table aiap97af_users. I'd put a random text for the password field there and then use the Forgot Password thingy.

**Comment by Klopko** [comment]
Yes, this is what came to my mind only after asking the question. Thanks for replying!

**Comment by tripatheea** [comment]
No problem. Good luck! :)

**Comment by pablorq** [comment]
Hi!

Can you fill in the db an application user & pass, like admin:admin. It's easier to handle.

Regards...
